name: Checkov Security Badge

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  checkov-badge:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Checkov
      run: |
        python -m pip install --upgrade pip
        pip install checkov
        
    - name: Run Checkov analysis and generate badge
      run: |
        python scripts/checkov-badge.py